FROM python:3.10

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code/app

ENV HOST=127.0.0.1
ENV PORT=8046

CMD ["python", "-m", "pong"]